### ISSUE TITLE
Ability to track Forms toolbar annotation's changes to enable custom save or cancel button to save or discard modified PDF snapshot.

### ISSUE THREAD

**Issue by hello2parth** [PDFTron/webviewer-ui#1005]
I have tried following ways to achieve the tracking of forms annotation changes.

<img width="1728" alt="Screenshot 2023-04-14 at 9 36 58 AM" src="https://user-images.githubusercontent.com/14799110/231940023-e67be14d-4a7a-4df4-9e62-3ed8d5c1c386.png">

1. I attached eventListener for `historyChanged` event and then using canUndo  method from `annotationHistoryManager`  class to track the changes. 

```
// assume PDFTron instance is available
const { documentViewer } = instance.Core;
const annotationHistoryManager = await documentViewer.getAnnotationHistoryManager();
annotationHistoryManager.addEventListener("historyChanged", () => {
     const annotationHistoryManager = await documentViewer.getAnnotationHistoryManager();
     const canUndo = await annotationHistoryManager.canUndo(); // canUndo will be true if there is a change which can be undone.
});
```
This is working for other annotation like Annotate . But it is not working for Forms annotation.

2. Then, I tried `annotationChanged` instead of `historyChanged`  with above code, but, that didn't work.

3. Then, I tried `UndoManager` from PDFNet to determine form annotation changes, after activating fullAPI(// fullAPI: true)

```
// assume PDFTron instance is available
const { documentViewer } = instance.Core;

documentViewer.addEventListener("documentLoaded", async() => {
     const { PDFNet } = instance.Core;
     await PDFNet.initialize();
     const undoManager = await PDFNet.UndoManager();
     /*  PDFNet.UndoManager method expecting id as argument as we have seen in inspect console. I am not sure which id I  need to pass. Further, value of undoManager coming as null which is blocking us to access any of UndoManager class methods listed at https://docs.apryse.com/api/web/7.3/PDFNet.UndoManager.html */
});
```

**Expectation / Requirement**
I am looking for the way

1. to track changes done via Forms toolbar annotation
2. to undo the changes
3. to redo the undo changes
 
**Why is this feature important to your users?**
This is blocking the development of digital signature feature.

**Desired timeline**
Immediate

**Comment by bollain** [comment]
Hello @hello2parth,

By design the changes made while in Form Builder are not tracked in the annotation history manager. This is because the adding and removing of widgets is not something that is tracked, only non-widget annotations. 

However, you could keep track yourself of when the form field place holders (the annotations that are used while in form mode) and decide whether you want to track how these added or removed.

```
  annotationManager.addEventListener('annotationChanged', (annotations, action, info) => {
    const annotation = annotations[0];
    if(annotation.isFormFieldPlaceholder()) {
      //decide what to do based on the action
      console.log({ annotation })
    };
  });
```
https://docs.apryse.com/api/web/Core.AnnotationManager.html#event:annotationChanged

We also have two events that get fired when you enter and leave the form building mode:
https://docs.apryse.com/api/web/Core.FormFieldCreationManager.html#.Events__anchor

Here you can detect if forms were added or edited, and then decide how to keep track of it.

If you need something more granular like keeping a record of the actual changes in the form field, like field names etc while in form builder, you can do so by adding this logic in the [FormFieldEditPopup](https://github.com/PDFTron/webviewer-ui/blob/10.0/src/components/FormFieldEditPopup/FormFieldEditPopupContainer.js) - perhaps by firing an event that marks the annotation as modified every time one its properties is changed. Alternatively, you could have an event listener on when the form field edit popup is closed, and automatically save. We currently do not have plans to add this functionality in the app itself, but you can always send in your requests via our [support system](https://apryse.com/support).

**Comment by hello2parth** [comment]
Thank you for the update. 

can you please help us in third point, how can we use PDFNet UndoManager class for the snapshot?

> 3. Then, I tried UndoManager from PDFNet to determine form annotation changes, after activating fullAPI(// fullAPI: true)
> 
> ```
> // assume PDFTron instance is available
> const { documentViewer } = instance.Core;
> 
> documentViewer.addEventListener("documentLoaded", async() => {
>      const { PDFNet } = instance.Core;
>      await PDFNet.initialize();
>      const undoManager = await PDFNet.UndoManager();
>      /*  PDFNet.UndoManager method expecting id as argument as we have seen in inspect console. I am not sure which id I  need to pass. Further, value of undoManager coming as null which is blocking us to access any of UndoManager class methods listed at https://docs.apryse.com/api/web/7.3/PDFNet.UndoManager.html */
> });
> ```

**Comment by bollain** [comment]
Hello @hello2parth,

The best approach for this question is to reach out directly to our [support team ](https://apryse.com/support). They will be able to guide you better and provide a quicker response.
