### ISSUE TITLE
[Bug] Undo Redo not working in ContentEditTool tool mode

### ISSUE THREAD

**Issue by ihassansattar** [PDFTron/webviewer-ui#1009]
**WebViewer version**
"@pdftron/webviewer": "^10.0.1",

**The current behavior**
The undo and redo functions break the pdf file content when I try to redo or undo using:

`viewerInstance.Core.documentViewer.getAnnotationHistoryManager().undo();`
In the example provided please wait for the file to load, and select Edit text option (it should be selected by default).

Make some text changes to the pdf file, and click on the undo on the far right in the sub header. Click on redo.

**The expected behavior**

Undo or Redo should not break the PDF file and just revert the last text change.

**Steps to reproduce**

Code Sandbox:
https://codesandbox.io/p/sandbox/angry-liskov-thqety

Please wait for the file to load, and select Edit text option (it should be selected by default).

Make some text changes to the pdf file, and click on the undo on the far right in the subheader. Notice the file breaks. Click on redo, and it is working fine again

**Comment by bollain** [comment]
Hello @ihassansattar,

Undo/redo operations are currently not supported in ContentEdit mode. The API you are calling is for annotations, which is a separate concept from content editing. This API is not meant to be called in content edit mode (we disable them in the UI), which is why you are seeing these issues. We are currently working on the next iteration for content edit, which will provide support for undo/redo. This is planned for release later this year.
