### ISSUE TITLE
[Bug] Cannot disable element noteState anymore

### ISSUE THREAD

**Issue by vekunz** [PDFTron/webviewer-ui#1025]
**WebViewer version**

10.2.3

**The current behavior**

After initializing the WebViewer, we want to disable the note state feature in the notes panel. But I think since we updated to 10.2.x this no longer work anymore.

```js
instance.UI.disableElements(['noteState']);
```

It seems that the data-element id changed. Previously it had `data-element="noteState"`, but now it includes a dynamic UUID, like `data-element="noteState-33f7dca7-bb68-6650-1cfe-52e39e3e431d"`.

**The expected behavior**

The noteState element should still have a generic element id, so we can disable this on any comment.

**Steps to reproduce**

https://showcase.apryse.com/

![image](https://github.com/PDFTron/webviewer-ui/assets/5724298/f5332486-220a-4743-8332-adaf7cee4686)

**Comment by bollain** [comment]
Hey @vekunz,

I see that we added this extra bit of info to the data element to fix another issue, but you are correct that we overlooked this use case. I'm adding this to our backlog to fix and will let you know when the fix is merged - the dataElemetn should not have this UUID. If you need a workaround, you can add an event listener on annotation added and disable the note state for each annotation being added - the UUID is the annotation ID. So it'd be something like:

```
// get the annotation from the annotation added event for example
instance.UI.disableElements([`noteState-${annotation.Id}`]);
```

**Comment by bollain** [comment]
Hi @vekunz,

This issue has been fixed in the master branch:
https://github.com/PDFTron/webviewer-ui/commit/971f93251fb45a91cde00f535c75d33282187725

This will be part of our 10.5 release due next week. 

Thanks for this report!
