### ISSUE TITLE
[Question] Can we publish this on npm so that we can have better control of loading?

### ISSUE THREAD

**Issue by etyp** [PDFTron/webviewer-ui#125]
Hello! Great library, we're happy users. Currently, we're using it locally but would prefer to install via npm so we have better control of code splitting and can avoid committing extra files to our project's git.

It seems like the project is well structured and built with webpack, so I'd imagine publishing to npm would be pretty straightforward.

Are there any plans to do this?

**Comment by justinjung04** [comment]
Hello! Thank you for your kind words :)
Publishing through npm is one of the idea we have in mind, but we don't have a timeline for it yet.
It's little tricky because this project is depending on WebViewer core, which is not ready to be published in npm.
We hope to iron these out and provide best solution to customers as soon as possible :)

**Comment by etyp** [comment]
Thanks for the response @justinjung04 ! Is WebViewer Core just what exists in this repo's `src/core/` directory? Or is it something else?

**Comment by justinjung04** [comment]
Core is not part of this repo, but part of the WebViewer download package. This repo's `src/core/` contains list of core APIs that were used in this project.

**Comment by justinjung04** [comment]
I will close this issue. Feel free to reopen it if needed :)
