### ISSUE TITLE
webviewer for blazor

### ISSUE THREAD

**Issue by potudopotudo** [PDFTron/webviewer-ui#332]
Any plans to release webviewer for Blazor? it's really difficult to integrate. It would be nice also to have a Typescript wrapper to work with events and objects because currently it's a hell. Thanks.

**Comment by ZhijieZhang** [comment]
**Any plans to release webviewer for Blazor? it's really difficult to integrate.** 
Could you elaborate more about what parts you find that are difficult to integrate? Currently we don't have a plan to make a Blazor integration sample. However, hearing feedbacks from you will definitely help us know the potential issues in general better.

Are you finding invoking WebViewer APIs difficult with Blazor? I'm not familiar with it but by reading [this doc](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.0) I think you can expose the `instance` variable on window and in C# you can call its methods.

**It would be nice also to have a Typescript wrapper to work with events and objects because currently it's a hell.**
You can see an experimental typescript definition file for WebViewer APIs here https://www.pdftron.com/documentation/web/frameworks/#typescript-definition-file

**Comment by potudopotudo** [comment]
Hi @potudopotudo  thanks for the quick reply. The typescript-definition-file will definetly help. But for example, I'm loading a 150 pages pdf, loading all the tumbnails for it, and even though it's asyn, the main PDF render gets blank, and after it I get all the thumbnails it gets normal again. But if I execute the demo app, the thumbnails load really fast, and I don't know how to achieve that. 

I don't want all that UI layaout built on it, I just want a canvas where I can draw my own annotations, move them around without being hooked to the AnnotationManager class. I want to get show the thumbnails in a custom carrousel for example.

What I found really difficult, is not having some kind of autocomplete to peek the API from typescript, but I'll definetly check that definition file and update you with any issues. Thanks!

**Comment by potudopotudo** [comment]
In Syncfusion for example they already have a Blazor PDFViewer implemented already: https://www.syncfusion.com/blazor-components/blazor-pdf-viewer not with so many functionallity as PDFTron, but It makes a lot of sense to have a Blazor integration.

**Comment by potudopotudo** [comment]
About the typescript d.ts file I found quite a lot of errors while trying to import it: 
![image](https://user-images.githubusercontent.com/3091146/63337499-fa833b00-c338-11e9-91a8-51e5b3846cbd.png)

**Comment by potudopotudo** [comment]
About the d.ts TypeScript file I found quite a lot of errors while importing it: 

![image](https://user-images.githubusercontent.com/3091146/63337561-171f7300-c339-11e9-8b4d-9c1982c69095.png)

**Comment by potudopotudo** [comment]
This is the only thing I got working so far, rest is broken symbols not recognizable by Typescript
[webviewer.txt](https://github.com/PDFTron/webviewer-ui/files/3520877/webviewer.txt)

**Comment by potudopotudo** [comment]
'CoreControls.ReaderControl;' doesn't seeme to be defined in that d.ts file

**Comment by aso777** [comment]
Hey @potudopotudo, a quick update on Blazor support. We have successfully integrated PDFTron's WebViewer with Blazor. We will send you a link once it's ready, sometime today.

**Comment by potudopotudo** [comment]
Thank you very much @aso777 Iooking forward for it. The bit I'm having problems specially is extracting all the thumbnails after the document loaded for the first time.

**Comment by aso777** [comment]
Here is our take on the integration of WebViewer inside of Blazor framework: https://github.com/PDFTron/webviewer-blazor-sample. Please take a look and let me know if you have any questions. It has been created using a server template.

**Comment by aso777** [comment]
For the thumbnail extraction you can call: https://www.pdftron.com/api/web/CoreControls.Document.html#loadThumbnailAsync__anchor. It would be best if you shoot us a quick email support@pdftron.com and we can continue from there.

**Comment by ZhijieZhang** [comment]
> The bit I'm having problems specially is extracting all the thumbnails after the document loaded for the first time.

I notice that there's [a similar sounding post](https://groups.google.com/forum/?nomobile=true#!topic/pdfnet-webviewer/Q_itXud-iOw.) that has been answered by one of my colleagues in the WebViewer forum.

You can see a concrete example in the [ThumbnailsPanel component](https://github.com/PDFTron/webviewer-ui/blob/master/src/components/ThumbnailsPanel/ThumbnailsPanel.js#L46). I believe when the main PDF is rendering, the `beginRendering` event will trigger and at this time we need to [cancel any thumbnails loading](https://github.com/PDFTron/webviewer-ui/blob/master/src/components/ThumbnailsPanel/ThumbnailsPanel.js#L219), otherwise the main PDF rendering may be blocked and result in what you are seeing.

If it happens to be you who posted in the forum, you can close this issue and my colleague Andy will assist you further in that post. If that's not the case, feel free to follow up! :)

**Comment by potudopotudo** [comment]
Hi I already checked, will make a workaround the Thumbnails Issue. I'll check the Blazor solution tomorrow. Thanks for the quick response!

**Comment by potudopotudo** [comment]
Everything is coming together, will keep you updated, thanks!
