### ISSUE TITLE
Lots of warnings for 'Unrecognised page child: viewport' in console when loading with WV Server

### ISSUE THREAD

**Issue by henry-chris** [PDFTron/webviewer-ui#368]
Hi - I'm getting this warning.

![image](https://user-images.githubusercontent.com/4165721/66228049-19991a80-e6a4-11e9-98f6-de097db97d51.png)

As you can see it pops up 40 times. Can you tell me what this warning is for and why it might be happening so many times?

Only seems to happen when loading a document with the WV server.

**Comment by henry-chris** [comment]
Sorry.  UI 5.2.3   WV Server 1.4.0 if that matters.

**Comment by ZhijieZhang** [comment]
Hi,

PDF workers for WebViewer have been updated recently to be able to read the information about `viewport` and pass it to WebViewer when it's loading a file. Currently the support for `viewport` hasn't been implemented on the WebViewer side so that's why you are seeing the warning message. This isn't a sign that some regressions have been introduced, but a new feature is waited to be implemented(though we don't have a timeline).

A `viewport` can contain a measure dictionary, and WebViewer can potentially read it and adjust scales of measurement annotations automatically when they're moved into that area.

Let me know if this answers your question!

**Comment by ZhijieZhang** [comment]
I will make a "fix" to not warn about a `viewport` tag. The fix will be available in the 6.0-beta, which should be available in the next few weeks.

I can also pick this fix to WebViewer 5.2.x if you want. Let me know.

**Comment by henry-chris** [comment]
Thanks.  No problems on my end.  There just wasn't much context and it was warning many times.  We are still having some problems here and there loading documents with the WV Server so I wanted to make sure it wasn't impacting that.

I would suggest giving more context about the warning if nothing else.  However, it is not impacting me in any way as long as I know the reason.

Thanks for the update.
