### ISSUE TITLE
Incorrect positioning of SignatureOverlay element in mobile and tablet modes

### ISSUE THREAD

**Issue by BaZzz01010101** [PDFTron/webviewer-ui#384]
To reproduce we can use chrome mobile emulation, but the problem is persist on real devices as well.

Steps to reproduce:

1. Open https://www.pdftron.com/webviewer/demo/ in chrome
2. Upload this [opendoc.pdf](https://github.com/PDFTron/webviewer-ui/files/3766524/opendoc.pdf)
3. Open Chrome DevTools (F12) and switch to mobile emulation mode
4. Add any signature (don't use the toolbar button, but click signature field in the document itself)
5. Add another signature using same method (in same or another field inside document)

Instead of signature modal (with drawing pad) the signature overlay with last created signature should appear (look at [screenshot](https://user-images.githubusercontent.com/11557955/67468813-d6531b80-f653-11e9-9f43-11842ecab8ce.png)).
As I understand, the position of this overlay is counted from position of signature button, but if the button is not visible, position became incorrect.

Place in source files:

ui\src\components\SignatureOverlay\SignatureOverlay.js

line: 91

```
  setOverlayPosition = () => {
    const { left, right } = getOverlayPositionBasedOn('signatureToolButton', this.overlay);
    this.setState({
      // TODO: remove the hard-coded value.
      left: left === -9999 ? window.innerWidth / 2 - 95 : left - 95,
      right,
    });
  }
```

**Comment by ZhijieZhang** [comment]
Hi!

Thanks for such detailed information and we can reproduce the issue you are seeing. I noticed that you've submitted a support ticket, so I think I will close this issue here and continue the conversation in the ticket.

For anyone else who's looking for a fix, it will be in the stable nightly build today, which means you can download the package tomorrow at https://www.pdftron.com/nightly/#stable/. The package name starts with `WebViewer_5.2.7`
