### ISSUE TITLE
Scrollbar not catchable

### ISSUE THREAD

**Issue by Camo30** [PDFTron/webviewer-ui#400]
Version: 5.2.4.72582 (not fixed in 5.2.7.72921)
Browser: Firefox 70.0.1

Steps to reproduce:

1. Open https://www.pdftron.com/webviewer/demo/
1. Open side panel (e.g. thumbnail view)
1. Point the cursor over the scrollbar, often there is a resizing grip visible, so the scrollbar is not always catchable

Expected behaviour:
The resizing grip should not be ahead of the scrollbar, but rather on the right side of it. Please see picture below

![2019-11-06 11_25_51-Greenshot image editor](https://user-images.githubusercontent.com/33700436/68290490-516ef580-0088-11ea-9218-a8d4dd47f05b.jpg)

**Comment by ZhijieZhang** [comment]
Thanks for the feedback. This makes sense.

The fix has been made in this commit https://github.com/PDFTron/webviewer-ui/commit/87112fd3c50114ffd854c52b0d8607d44526fac1 so you can just pull from master.

Let me know if you'd like me to send you a new minified `webviewer-ui.min.js` that contains the fix. The fix isn't in the nightly build yet but please also let me know if you'd want me to pick the commit to our private repo. Otherwise the fix will be included in the next WebViewer release(either 5.2.9 or 6.0-beta).

**Comment by Camo30** [comment]
Thank you! It's sufficient when the fix will be included in the next non-beta WebViewer release.

**Comment by Camo30** [comment]
I tried it with the nightly from this morning and it's fixed. Thank you!
