### ISSUE TITLE
Enhancement - Provide better API for hiding/showing annotations

### ISSUE THREAD

**Issue by henry-chris** [PDFTron/webviewer-ui#448]
Currently, your workflow for selectively hiding and showing annotations is the following (in most cases) -
1. core.deselectAllAnnotations()
2. core.selectAnnotation()  (or multiple annotations)

I propose something close to the following - 
1. core.deselectAllAnnotations([<list of excepted annots])  (optional arg)
OR
2. core.deselectAllAnnotsExcept([])

And then on the flip side - 
1. core.selectAllAnnotations([<list of excepted annots])  (optional arg)
OR
2. core.deselectAllAnnotsExcept([])

This allows cleaner code and less events under the hood in many cases.  There aren't many places where the code needs this logic, but the code that does use it gets triggered many times.  

While it doesn't show on your standard UI very well, we(my customized UI) highlight the annotation when selected and do some other things.  So, unless we do some parsing beforehand, whenever a note is clicked the highlight visibly blinks when it's deselected, then selected again.  

We've also had to do other custom things to get selections to work correctly, and have submitted Issues.

Here is one example of a fix from a previous Issue.
![image](https://user-images.githubusercontent.com/4165721/71379918-dfe4fb00-2592-11ea-8859-777a5e0e22a1.png)

Now, it looks like you may have solved some of the problems based on code in 6.0, but it is still a worthwhile addition I think.

I bring this up because I worked on a map based GUI previously with event based selection/deselection of items.  Adding these types of methods greatly simplified many things.  It mainly solved the following problems ->
1. Order of execution for event based code
2. Less events and executed code overall, which helped greatly with large data sets (in this case many annots)
3. Negated the need to batch events since we now only have 1 in many cases
4. Simplified synchronization of states on the back-end (which may or may not apply for you as much)

I've meant to bring this up for a while, but never got around to it.  I hope you agree with my thoughts.

**Comment by ZhijieZhang** [comment]
Thanks for the proposal!

To select all the annotations except certain ones, you can use `annotManager.getAnnotationsList`, filter the returned array and pass it to `annotManager.selectAnnotations`. Currently we don't have a `deselectAnnotations` API so we have to do it in two steps (deselectAllAnnotations and selectAnnotations). Would it be good enough if we provide you with a `deselectAnnotations` API?

Maybe I'm not fully understanding your requirements here, but a `selectOnly` API sounds more like what you are looking for? The use case for this API is when you want to set exactly which annotations should be selected and you don't want to care which annotations are currently selected or not. The `selectOnly` API will be more ideal than calling `deselectAllAnnotations ` and `selectAnnotations` because it will only redraw annotations once, which should solve your highlight blinking issue.

However, `selectOnly` doesn't necessarily mean the `annotationSelected` event will only be triggered once. If calling his API deselects any annotations, we should expect that `annotationSelected` is triggered twice, one with 'selected' and the other with `deselected` as their second argument. So it sounds like this doesn't actually solve the issues you brought up at the end? One possibility is to change the event interface so that annotationSelected will only be triggered once. For example:
```javascript
annotManager.on('annotationSelected', ({ selected, deselected }) => {
  ...
})
```

Does the above interface work well for your use case? Changing the event handlers to be this is a breaking change so we probably need  to think about it more thoroughly. If we made this change then we may also want to make a similar change for the annotationChanged event to keep it consistent, `e.g. { added, modified, deleted }`

Let me know if I'm missing or misunderstanding something.

**Comment by henry-chris** [comment]
> To select all the annotations except certain ones, you can use annotManager.getAnnotationsList...

Yes, we could do that but this is more a proposal to allow the core logic of the UI to change, too.


> Does the above interface work well for your use case? 

Trying to follow all of your post.  So, would you do the following?:

1. Create SelectOnly API
2. Re-do event structure

If so, then that might work, I'd have to look more carefully, though.

Here's the most basic scenario to prevent.

1. User has 1 annot selected.  
2. User clicks already selected annot in NotesPanel
3. Currently selected annotation triggers no events.  It is not deselected (because it doesn't need to be) and it's not selected (because it's already selected).

This extrapolates out to many selections/deselections as well as other use cases.  Basically, give the user a contextual way to stop triggering unneeded events. 

There are some corner cases to consider.  Such as if UI elements need refreshing, but then that can be handled with already existing APIs or iterated upon.

**Comment by ZhijieZhang** [comment]
I just want to follow up to see if this is still something that you are looking for? We're preparing for the 8.0 release and there'll be plenty of API changes. Let us know if anything related to this has been changed.
