### ISSUE TITLE
Stamp tool does not work in IOS 13

### ISSUE THREAD

**Issue by henry-chris** [PDFTron/webviewer-ui#457]
Load **Demo Website** on device using IOS 13.  
Attempt to use Stamp tool.
Tool doesn't work.

**Comment by ZhijieZhang** [comment]
Thanks for reporting the issue. I just made a fix to it and is waiting for the review. I will post again after the fix is available in the nightly build. Thanks for your patience!

**Comment by ZhijieZhang** [comment]
Hello,

Sorry for the delay for the reply. The fix is available in WebViewer 6.0.4. If you are using 5.2.8 then it's contained in the stable nightly build. You can download the nightly build here https://www.pdftron.com/nightly/#stable/.

I will close the issue for now since I verified the fix worked. But do feel free to reopen if you found any other issues and would like to discuss more. Thanks and have a good day!
