### ISSUE TITLE
Post-install extraction keeps failing when running npm install

### ISSUE THREAD

**Issue by notarock** [PDFTron/webviewer-ui#487]
### Post-install extraction keeps failing when running npm install

We have integrated webviewer in our react app, but we keep running into an issue where `@pdftron/webviewer-downloader`'s post-installation script keeps failing randomly. 

![image](https://user-images.githubusercontent.com/25652765/73556088-b84c4280-441c-11ea-9926-4f8cf9a1003c.png)

The build scripts fail with the error:
```
Extracting WebViewer...events.js:187
      throw er; // Unhandled 'error' event
      ^
Error: invalid central directory file header signature: 0x81ff0020
    at /builds/civalgo/portal/node_modules/yauzl/index.js:258:70
    at /builds/civalgo/portal/node_modules/yauzl/index.js:631:5
    at /builds/civalgo/portal/node_modules/fd-slicer/index.js:32:7
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5)
Emitted 'error' event on ZipFile instance at:
    at emitError (/builds/civalgo/portal/node_modules/yauzl/index.js:232:8)
    at emitErrorAndAutoClose (/builds/civalgo/portal/node_modules/yauzl/index.js:227:3)
    at /builds/civalgo/portal/node_modules/yauzl/index.js:258:42
    at /builds/civalgo/portal/node_modules/yauzl/index.js:631:5
    at /builds/civalgo/portal/node_modules/fd-slicer/index.js:32:7
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! civalgo@4.2.0 download-webviewer: `npx @pdftron/webviewer-downloader --path ./public/webviewer`
```

Our pipeline is simply:

```
npm i
npx @pdftron/webviewer-downloader --path ./public/webviewer
```

It also happens once in a while installing locally, with the same error message. Do you have any idea how to fix this? Rerunning failed pipelines is a bit annoying...

**Comment by SamuelTSO** [comment]
We have the same issue at the our company, it's very annoying!

**Comment by ZhijieZhang** [comment]
Hi guys,

Thanks for bringing this to our attention! I just tried `webviewer-downloader` multiple times locally but wasn't able to reproduce the issue. It's kind of unfortunate that the issue seems to be from a library that `webviewer-downloader` depends on, which means we might not be able to fix this issue. 

I found some similar issues in that github repo https://github.com/thejoshwolfe/yauzl/issues/69, https://github.com/thejoshwolfe/yauzl/issues/98 and https://github.com/thejoshwolfe/yauzl/issues/60.

However these issues might be unrelated since I don't think we are using Mac Archive Utility to create the `WebViewer.zip`. I will take a look at this issue and see if I'm able to figure something out.

In the meanwhile, we will investigate if it's feasible to put WebViewer worker files on npm so that you don't need to use the downloader to download them in your pipeline.

Sorry for the inconvenience!

**Comment by notarock** [comment]
For our pipeline, we are using the [node](https://hub.docker.com/_/node/) official image `node:12.14.0`. Hope that helps!

**Comment by ZhijieZhang** [comment]
Hi guys, we made an attempt to fix this issue. Can you try the latest version and see if the issue is fixed? To install the latest `@pdftron/webviewer-downloader` in your pipeline please make sure that git is installed as well in that environment.

**Comment by notarock** [comment]
After a couple of test, it seems to work file now. Thanks!

**Comment by igl** [comment]
We still face this issue on a regular basis running `yarn install` in our github action pipeline.

**Comment by igl** [comment]
I remove node v12 from the pipeline. No issues with v10 so far
