### ISSUE TITLE
Creating rubber stamps with custom icons

### ISSUE THREAD

**Issue by elephantcatdog** [PDFTron/webviewer-ui#540]
Version: 6.1.1

Is there a way to add new icons to the RubberStampAnnot Icon properties? I could not find a way to do so, reading the [documentation](https://www.pdftron.com/api/web/PDFNet.RubberStampAnnot.html#toc0__anchor). The Icon properties seem to generally correspond with the options visible in the dropdown menu for the rubber stamps, minus a few.

I want to be able to create custom rubber stamps to add to or replace the defaults. Is this done with the RubberStampCreateTool? The documentation says that it creates StampAnnotations, so then when/where is RubberStampAnnot used?

**Comment by ZhijieZhang** [comment]
Thanks for bringing this up. 

Being able to add custom icons in the UI is actually on our roadmap. We don't have a timeline for this feature yet. 

However, if you can elaborate more about how important this is to you, that can help us evaluate and prioritize the feature.

`RubberStampAnnot` is a class that belongs to `PDFNet`, which is full api related(for more information please see https://www.pdftron.com/documentation/web/guides/full-api/). The RubberStampCreateTool doesn't require full api to be enabled, thus not using the `RubberStampANnot`.

Please let me know if you have further questions regarding this. Thanks!

**Comment by sam-stuart-bentley** [comment]
Hi, we have users that are asking for this functionaity, and what they'd like to do is create libraries of repeatable stamps for common purposes.  Often times, these can be simple letter initials within a circle to call attention to a common issue on a PDF, but in some cases, they ask that we allow them to create symbology from CAD programs and import the CAD symbols so that the symbols that they use to identify issues in a CAD program, matches what they use on PDF's.  I'm happy to give more feedback if needed.

**Comment by ZhijieZhang** [comment]
Thanks for the information.

Just want to clarify that the CAD symbols are some common images that can be used to mark things in CAD programs, and you have users who are asking for a way to import these images into WebViewer so that they can be used as marks in PDF documents as well?

In this case would it help if there's an extra `+` in the stamp overlay(which shows when you click the rubber stamp tool button in the misc tool group) that lets the users be able to add their own images as custom stamps? Also WebViewer will provide APIs for importing stamps and export stamps(an array of base64 strings).

**Comment by henry-chris** [comment]
Yes, basically users want to have custom symbols for marking up the document.  And have those symbols be usable across the platform for their own organization.

We would allow them to upload something.  Then download/link to the dynamic list of symbols for each customer.  

So, my thought would be something like the current tool (Rubber Stamp) you have, but allow a Promise to to return (or many promises) with symbols that will fill the tool.

Then storage of the symbols could be anywhere I think.  Unless there are Cross-Origin considerations, but we could get around that.

Are the Rubber Stamps all images?  It seems like they scale pretty well on the document and I haven't looked very closely.

Since IE11/Old Edge is being deprecated by many sites, it may  be a good idea to try to implement an SVG version of this, too.  I know those browsers had security violations for SVGS, but newer browsers seem to allow them in many cases.  I guess we'd need to convert those to images when serializing, though.

**Comment by ZhijieZhang** [comment]
Sorry for the delay in the reply!

Rubber stamps are just predefined stamp annotations. Currently a stamp annotation can be created programmatically given a base64 image string.

I will forward this to the team and see if we have any plans or further thoughts. Let me know if you have a timeline or if this is an urgent feature you need to have. Thanks!

**Comment by ZhijieZhang** [comment]
I think the feature that is being looked for has been available for a while now. The API is https://www.pdftron.com/api/web/Tools.RubberStampCreateTool.html#setCustomDrawFunction.

Closing for now but feel free to reopen it to discuss if you guys have other questions.

**Comment by jloApryse** [comment]
update to above link:  https://docs.apryse.com/api/web/Core.Tools.RubberStampCreateTool.html#setCustomDrawFunction__anchor
