### ISSUE TITLE
Release management versions not tagged

### ISSUE THREAD

**Issue by peterpeterparker** [PDFTron/webviewer-ui#541]
Hi,

I would like to not report an issue but suggest an improvement in your releases management.

According README and [CHANGELOG](https://www.pdftron.com/documentation/web/changelog/v6-2-0/) current version is v6.2.0.

However, no releases have been [tagged](https://github.com/PDFTron/webviewer-ui/releases) in this repository since v5.2 in August 2019.

I think it would be improve the quality and traceability if such tag would be applied.

Thx in advance
David

**Comment by ZhijieZhang** [comment]
Hi David,

I'm not too familiar with how `git tag` works, so please correct me if I'm wrong :)

I did some research and it seems that repositories that utilize tags often have only one branch(master). I guess this makes sense, because then they can use tag to quickly trace back to the previous releases, and fix issues or do something else that's needed.

For WebViewer and WebViewer UI, `master` is the development branch, and we will branch off of `master `to make our release branches. Currently the default branch for WebViewer is `6.2`, which indicates that the latest official version is `6.2`. 

By having release branches for every minor or major versions, I feel like this is essentially the same as having tags? Because if I'd like to fix a bug for the previous releases, I can just do `git checkout 6.1`.

It looks like if we make a release https://github.com/PDFTron/webviewer-ui/releases, then github will automatically tag the version and commit for us. I think the reason why we stopped making UI releases specifically is that we post changelogs on our website. Those include changes in both WebViewer and WebViewer UI, which makes me feel a bit redundant to also make a release in this repo. And I just feel it's nice to have things just in one place :)

Please let me know if this answers your questions. Have a nice day!

**Comment by peterpeterparker** [comment]
Thank you for your answer.

Yes it does answer my questions, specially as I understand now your release process.

That being said, I personally think that it it isn't the same as having tags notably because it would be much appreciated to be able to compare also changes between any tips of versions including the minor and patch one.

That's why thee Release/Tags features of GitHub is so useful.

I checked for instance what [Ionic](https://github.com/ionic-team/ionic) does and their pattern is close to yours. Since they version 4 they create branches for all their major and minor releases, like 4.0.x, 4.1.x etc. but if you check their [releases](https://github.com/ionic-team/ionic/releases) they do also apply a tag on each release which makes comparison easier, here for instance v5.0.5 vs 5.0.4 https://github.com/ionic-team/ionic/compare/v5.0.4...v5.0.5

Another concrete example: I opened this week a support request because custom headers weren't transmitted with the request using Webviewer UI. As always you support answered quickly and the solution was to upgrade from v6.2.0 to v6.2.1. Even though it worked out like a charm, I would be interested to now what was modified but, I can't compare easily these two versions currently as there is no tags.

That's why I think it would be an asset total advantages of the tags and releases of GitHub.

What do you think?

P.S.: Regardless of if you are agree or not, you can of course close this "feature request". To me it's clear that is is a plus but I won't argue more, no worries if you do so, all cool.

**Comment by ZhijieZhang** [comment]
Thanks for the reply!

It definitely helps me understand better the usage of tags(release) with a concrete example. I think this is a reasonable request, and after talking to the team, we decide to restart doing this process in the future versions.

Regarding the custom headers fix in 6.2.1, unfortunately the changes in the code won't be available in this repo. The fix is in WebViewer, and this repo - WebViewer UI is just a UI that sits on top of WebViewer. The bottom of [this guide](https://www.pdftron.com/documentation/web/guides/default-ui/) has an image that shows the connection between them.

Anyways, I think doing tags is still beneficial since we may be curious about changes only in the UI.

Thanks again for bringing this up, and have a nice day!

**Comment by peterpeterparker** [comment]
@ZhijieZhang thank you for having taking in account my request and I'm really happy to hear that in the future, you are going tag and release again this repo 👍
