### ISSUE TITLE
Text Popup Link Tool not disabled in Read-Only mode

### ISSUE THREAD

**Issue by henry-chris** [PDFTron/webviewer-ui#571]
I may be wrong here, but I couldn't find something that we are doing which would supersede the read-only mode you provide.

If you set the document to read-only a lot of items disappear from menus.  One that doesn't is the link tool in the Text Popup component.  Since the Link acts as an annotation of sorts and is propagated to the XFDF it should probably be disabled by default.

**Comment by ZhijieZhang** [comment]
hmm, I think this issue should be fixed in this commit https://github.com/PDFTron/webviewer-ui/commit/5d7bad66d8b810d63bcc8dbb35a52ad7f41897de.

I tried with the following code but wasn't able to reproduce the issue:
```javascript
Webviewer(
  {
    initialDoc: hashFile,
    path: '/lib',
    enableReadOnlyMode: true,
  },
  document.getElementById('viewer')
).then((instance) => {});
```
and
```javascript
Webviewer(
  {
    initialDoc: hashFile,
    path: '/lib',
    // enableReadOnlyMode: true,
  },
  document.getElementById('viewer')
).then((instance) => {
  instance.annotManager.setReadOnly(true);
});
```

If you try the latest version are you able to reproduce the issue? If yes, could you show me the code you used to reproduce the issue?

**Comment by henry-chris** [comment]
Well. That's absolutely my fault.  I did not merge your newest GUI files in, only the Core.

Can confirm that it's been fixed.  My apologies.
