### ISSUE TITLE
Tooltip component sometimes breaks app

### ISSUE THREAD

**Issue by henry-chris** [PDFTron/webviewer-ui#575]
We see this very randomly and sporadically.  I haven't figured out what's causing it yet, and we can't reproduce it readily.

It seems that somehow the following code in ToolTip.js cannot find 'top' of undefined.  That's the error we get in this file.

![image](https://user-images.githubusercontent.com/4165721/79520260-f02a5580-801b-11ea-99ee-087dd476ce6f.png)

I'm guessing that it occurs when the `bestLocation `cannot be found from the `.find()` function.  I did not get a shot of the specific line of code of the error sadly.

Putting some null checks and logging around each access of `locationTopLeftMap` on our end to see if I can pinpoint the cause.  Just wanted to let you know.

**Comment by ZhijieZhang** [comment]
Thanks for bringing this up and sorry for the delay in the reply. I'm still kind of busy with other stuff.

If bestLocation cannot be found it means the there's no place in the viewport that can show the entire tooltip component. I can't think any cases where this can happen, but I must miss some edge cases since you were seeing errors about this.

I think I'm going to add a fallback location to fix this issue.

**Comment by henry-chris** [comment]
No worries.  Ya, it's strange as it doesn't seem like it's possible.

Once you add this one, i'll take a nightly and start incorporating it when possible.  I think we've heard back on everything.

**Comment by ZhijieZhang** [comment]
Just pushed a fix to this issue. The fix should be available at tomorrow's nightly build.
