### ISSUE TITLE
Measurement Tools Bugs

### ISSUE THREAD

**Issue by elephantcatdog** [PDFTron/webviewer-ui#610]
Version: 6.3.0

In the [measurement tools demo](https://www.pdftron.com/webviewer/demo/measurement-tools), an area measurement markup placed in the approximate middle of the page will have a style popup that gets cut off at the bottom. My window height is 937px.
![image](https://user-images.githubusercontent.com/37936169/82098584-d8052f00-96ca-11ea-98c9-c551f2e25ec7.png)

If the window is narrow enough that the measurement overlay overlaps the pdf, any measurement tool will be hidden behind the measurement overlay while drawing. The area and perimeter tools will not allow a node to be placed behind the overlay at all.
![image](https://user-images.githubusercontent.com/37936169/82100263-e7867700-96ce-11ea-9b8b-a6999447139e.png)
Consider allowing the overlay to become transparent or move when the user is drawing and hovers on it.

I will add any other measurement issues as I find them. Thank you.

**Comment by ZhijieZhang** [comment]
Thanks for the feedback!

For the first issue I think we will resolve it by just making the popup draggable. So in this case you can drag it to somewhere else to see the `Precision`.

The second issue might take some time to resolve. I will need to poke around.

**Comment by henry-chris** [comment]
@ZhijieZhang  As a quick addendum. 

In the demo you have a 'Enable Snapping' option.  We are placing that option directly in the tool popup as a check box (but not in the annotationStylePopup).  I think in the 'MeasurementOptions'.

Do you think that's a valuable option to put in stock webviewer?  I ask because we like to have as few changes as possible to the standard viewer.

**Comment by elephantcatdog** [comment]
Hi @ZhijieZhang,
I've found another issue.

When snapping is enabled on a tool, the annotation snaps to lines during the initial drawing, but not when editing it. This occurs for any tool with snapping enabled, as in the [snapping demo](https://www.pdftron.com/webviewer/demo/snap-to-objects), not just measurement tools.

I also noticed that when using the area or perimeter tools (or any tools that use clicks to place a point), both left-clicking and double-clicking can end an annotation. Using left-clicking to end the annotation also brings up the left-click context menu. It would be nice if this menu didn't appear when ending an annotation, as it could be confusing to users when they expect the annotation menu.
![image](https://user-images.githubusercontent.com/37936169/82500396-ec756d00-9ab8-11ea-9224-9f3ca8499150.png)
![image](https://user-images.githubusercontent.com/37936169/82568530-93531b00-9b44-11ea-9d38-46fb24cbef38.png)

**Comment by henry-chris** [comment]
@ZhijieZhang  Another issue seems to be that the Measurement Overlay in the bottom right is changeable when the viewer is in Read-Only.  

I think at least.

Should we split any of these up?

**Comment by ZhijieZhang** [comment]
I think it's ok to have all of them in this one issue. I'm just going to list all the feedback below:

1. - [ ] The bottom of the style popup is cut off in some cases
2. - [ ] The measurement overlay covers part of a measurement annotation 
3. - [ ] When snap mode is enabled, dragging the control point of a measurement annotation doesn't snap the point
4. - [ ] Finishing an annotation by left click will select it sometimes, which can be confusing to users.
5. - [ ] The text input in the measurement overlay is still adjustable in the read-only mode.

I will edit this reply as we fix these issues.

Regarding 3, we've noticed this recently. After some investigations, it turns out quite some work needs to be done to make this work as intended. For now we've put it into our backlog, and will work on it in the future.

If any of the issues above are urgent to fix for you or if you have any other concerns, please let me know.
