### ISSUE TITLE
Note Annotation create crashes the app

### ISSUE THREAD

**Issue by michaelpeterlee** [PDFTron/webviewer-ui#880]
STEPS TO REPRODUCE:
1. git clone > npm install > npm run download-webviewer> npm start
2. Annotate > Note > Create note

ERROR:
TypeError: null is not an object (evaluating 'mount.appendChild'). AnnotationNoteConnectorLine.js:17

-

I commented-out ContentArea.propTypes.onTextAreaValueChange to no avail [solves error below].

Warning: Failed prop type: The prop `onTextAreaValueChange` is marked as required in `ContentArea`, but its value is `undefined`.
    in ContentArea (created by NoteContent)
    in NoteContent (created by Note)
    in div (created by Note)
    in Note (created by ForwardRef)
    in div (created by ForwardRef)
    in div (created by ForwardRef)
    in ForwardRef (created by NotesPanel)
    in div (created by NotesPanel)
    in NotesPanel (created by App)
    in div (created by ForwardRef(MotionComponent))
    in ForwardRef(MotionComponent) (created by RightPanel)
    in PresenceChild (created by AnimatePresence)
    in AnimatePresence (created by RightPanel)
    in RightPanel (created by App)
    in div (created by App)
    in div (created by App)
    in App (created by HotExportedApp)
    in AppContainer (created by HotExportedApp)
    in HotExportedApp
    in I18nextProvider
    in PersistGate
-

**Comment by bollain** [comment]
Hi @michaelpeterlee, thanks for reaching out. I looked at this and the reason is that when you start the app from this repo, it uses a starting html file that is missing a `div` that we use for the React portal component of the line connector. I will make a PR to fix this, but in the meantime you can add this line:
```
    <div id="app"></div>
     ///Add the line below
    <div id="line-connector-root"></div>
```

To this file:
https://github.com/PDFTron/webviewer-ui/blob/7.1/src/index.html

The issue with the warning for the proptypes is separate, and won't crash the application. We are currently looking into that one.

**Comment by michaelpeterlee** [comment]
That corrects the issue thanks.
