### ISSUE TITLE
Annotations context menu unavailable if side menu open

### ISSUE THREAD

**Issue by peterpeterparker** [PDFTron/webviewer-ui#900]
Issue:

The context menu of the annotations does not appear if side menu is opened.

Expected:

The context menu of the annotations should be available regardless of the menu state.

Screenshots:

<img width="1052" alt="Capture d’écran 2021-02-03 à 09 43 13" src="https://user-images.githubusercontent.com/16886711/106720991-5f515480-6604-11eb-9349-fdce40691531.png">
<img width="1052" alt="Capture d’écran 2021-02-03 à 09 43 20" src="https://user-images.githubusercontent.com/16886711/106720999-61b3ae80-6604-11eb-9dc0-750b9e4ab8df.png">

**Comment by ZhijieZhang** [comment]
Thanks for bringing this up and sorry for the delay in the response! 

I believe this issue has been fixed in the experimental build. Currently we are doing some final round of testing on the experimental build. I expect that around next two weeks we will release a new version that includes the fix to this issue.

Let me know if you have any concerns!

**Comment by peterpeterparker** [comment]
That works for me, thx 👍
