### ISSUE TITLE
[Feature] Event on Drag and Drop in Left Panel

### ISSUE THREAD

**Issue by piu130** [PDFTron/webviewer-ui#904]
Our customers would like to drag and drop pages in the left panel from one browser window to another.
This would copy the selected page(s) from the first window to the second window.

To implement this, **we need a drag-event when the user starts dragging in the left panel**:
```typescript
instance.on('thumbDrag', () => { /* do some stuff */ })
```
The payload does not matter for us, since we can get the selected pages with `intance.getSelectedThumbnailPageNumbers()`.
Next, **we need a drop-event when the user drops the pages in the left panel**: 
```typescript
instance.on('thumbDrop', (dropIndex: number) => { /* do some stuff */ })
```
Here the payload matters, so we know, where to insert the pages.

Could you implement those two events as soon as possible, so we can implement this drag and drop behavior in our webviewer?

**Comment by bollain** [comment]
I will add this feature request to our backlog, but I can't provide a timeline on where we may get to implement these.

However, you could start implementing this behaviour by forking the repo and customizing the drag/drop handlers in the ThumbnailsPanel:
https://github.com/PDFTron/webviewer-ui/blob/7.2/src/components/ThumbnailsPanel/ThumbnailsPanel.js#L113

As an aside, we have a demo that shows how drag and drop works between to instances of the viewer, but in the same page:
https://www.pdftron.com/documentation/samples/js/thumbnail-controls/
https://www.pdftron.com/samples/web/samples/pdf-manipulation/thumbnail-controls/

We have previously looked at how it would work for dragging between browser windows, and we found that it could be possible to do it using the dataTransfer API:
https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer

The tricky part, is that the page data needs to be available at the start of the drag, so we would have to store a blob of every page or every selected page. This was causing performance issues due to needing a blob of each page. 

Let me know if you have further questions. For now I will add the feature request for the events to the backlog. As I noted, we don't have a timeline for when it will be available but if it does get worked on we'll let you know when it's available in an experimental build to test out and the estimated official release date.
 
If this is a critical improvement for you, and you need a fixed timeline for this to be completed by, then the next step would be to do a paid custom engineering project. If you are interested in that, please fill in this form.
https://www.pdftron.com/form/professional-services/

I will close this issue as it is now being tracked through FreshDesk ticket #20177. It is best to keep the thread in a single place for tracking purposes.

**Comment by jasonhu777** [comment]
Hello,

I am currently working on "thumbnailDragged" and "thumbnailDropped" events. And I would like to ask a clarifying question regarding "thumbnailDropped".  Is the payload "dropIndex: number" referring to the page indexes at the begining of drag, or the indexes of where pages being dropped?

**Comment by piu130** [comment]
Hi @jasonhu777 

Thanks for working on this.
We would like to call `doc.insertPages(...)` afterwards, so we can cut the pages from the 'dragging window' and insert them in the 'dropping window'.
So we need to know the indexes of where pages being dropped.

Example:
User selects page 5 from window1 and drops between page 2 and 3 in window2.
We now cut/copy page 5 from window1 and insert it between page 2 and 3 in window2. So we need either dropIndex 2 or 3 (which one does not matter, because we can always do -1/+1).

**Comment by jasonhu777** [comment]
Hi. I just published a testing env for `thumbnailDragged`, `thumbnailDropped` events, you can view the events being triggered in the console. Let me know how it works for you and any questions you have!
https://jasonhu-pdftron.web.app/thumbnailDragDropEvents/

**Comment by piu130** [comment]
This looks great. I think this is what we needed.
Thanks for implementing it!

**Comment by jasonhu777** [comment]
You are welcome, this branch will be merged to master after review. :)

**Comment by piu130** [comment]
@jasonhu777 is your feature already integrated in the new WebViewer 8.1? We could not find any hint in the documentation/source.
Do you have a roadmap for this?
