### ISSUE TITLE
[Bug] Signature and custom stamps username does not use AuthorMap when set for annotations

### ISSUE THREAD

**Issue by henry-chris** [PDFTron/webviewer-ui#915]
**WebViewer version**
7.3.2
**The current behavior**
When using IDs/GUIDs for annotations and user ids there is no single store of info / single place to get data from.
So, if I set the current user to a GUID I would expect a selector or function that is the single source of truth for how to display the user name.  Right now that exists with only annotations with 'SetAnnotationAuthorMap'.  

When using the signature or custom stamps the GUID is shown because the GUID is what exists in Redux.

**The expected behavior**

I give PDFTron a way to parse user information such as GUID -> Name conversion.   PDFTron uses that everywhere without question when displaying the information.

**Steps to reproduce**

Make the current user an ID/GUID.  Create a Text Signature or a custom stamp.

**EDIT:  Did not realize that ''core.getCurrentUser' calls 'AnnotationManager.getCurrentUser()'. Just change this to .getDisplayAuthor and I think that fixes everything?  Or maybe only the UI components that display things to the user should use that function.

More EDIT:  I guess you need an annotation to get the display author and trigger the AuthorMap.  Not sure of the correct course, then.**

**Comment by bollain** [comment]
Hi @henry-chris,

I've looked at this issue and I am able to reproduce the behaviour you describe. As you point out, the problem is that we don't have an annotation to use with the AuthorMap at the time, and hence we simply display the ID/GUID. I have discussed this with the team, and we have decided to change the AuthorMap to instead of taking an annotation, take an ID; so the mapping would be from ID/GUUID to display name. That way we can simply map the current user ID into the correct display name.

As this will be a breaking change we will make it part of our next major release. An Item has been added to our internal backlog, I will provide an update here when this is scheduled for release.

**Comment by bollain** [comment]
Hi @henry-chris,

The update to the Author Map has been completed and is part of our 8.0 release, which you can read more about [here](https://www.pdftron.com/documentation/web/get-started/migrating-to-v8/#getdisplayauthor-parameter-change)

You can download it from our [downloads page](https://www.pdftron.com/documentation/web/download) or check out the 8.0 branch in this repository.
