### ISSUE TITLE
[Feature Request] optimization script for automated build pipelines

### ISSUE THREAD

**Issue by TetsuGuy** [PDFTron/webviewer-ui#924]
Hi,

we are using Azure Pipeline for building our project. The optimization script is great, since it reduces the size of our final product by 50%. Unfortunately it requires user input to set up. It would be great to just have starting arguments like 
`npm run optimize --fullapi --salesforce` etc.
 
The inclusion of Pdftron has a big impact on build size (size increased from ~20MB to ~90MB) so the reduction is greatly appreciated.

**Comment by bollain** [comment]
Hi @TetsuGuy,

We actually just updated our optimize-for-prod script to take arguments without user input. However, it has not been added to our latest release. Therefore, I created a gist with the updated script - you can simply copy this into your project.

Example of use:
```
$ npm run optimize -- auto --backupFiles=true \
            --usingWebViewerServer=false \
            --willConvertToXod=false \
            --needClientSideOfficeSupport=true \
            --legacyOffice=false \
            --type=false \
            --salesforce=false \
            --deleteUnused=true
```

And the  updated script can be found here:
https://gist.github.com/bollain/3f40fa58920ee4f1f68a5d040b940d2f

Let us know if you have further questions about this. This will be part of our next release.

**Comment by TetsuGuy** [comment]
I think your parameter `optimizeOptions.deleteUnused` is boolean which means the deletion step on `auto` will never happen since it's checked for the string "y"

```
if (mainOptions.command === 'auto') {
        result.delete = optimizeOptions.deleteUnused; // here it should be optimizeOptions.deleteUnused ? "y" : "n"
      }
      if (result.delete === 'y') {
          ...
```

**Comment by bollain** [comment]
Hi @TetsuGuy, 

You are right, this value should be set to a string and not a boolean. We have fixed it on our end, but in the meantime you can tweak it since this is not released yet.

As for your second question, you are correct. We have a block in the script that installs some dependencies if they are missing, but it seems we missed `command-line-args`:
```
  try {
    require.resolve('prompt');
    require.resolve('fs-extra');
    require.resolve('archiver');
  } catch (e) {
    console.log(CYAN, 'Installing required dependencies...', RESET);
    await exec('npm i prompt --save-dev && npm i fs-extra --save-dev && npm i archiver --save-dev');
  }
```

You can simply add `command-line-args` as a dev dependency and this will fix this issue. 

I will close this now, but if you have any other questions feel free to re-open this issue.
